version: '3.8'

services:
  exulu-worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
      args:
        NODE_ENV: ${NODE_ENV:-prod}
        NPM_TOKEN: ${NPM_TOKEN}
    container_name: exulu-worker
    ports:
      - "9002:9002"
    environment:
      - NPM_TOKEN=${NPM_TOKEN}
      - NODE_ENV=${NODE_ENV:-prod}
      - PORT=9002
    restart: unless-stopped